services:
  platform:
    build: ./platform
    ports:
      - "3000:3000"
    env_file:
      - ./.env.docker
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "80:80"
    env_file:
      - ./.env.docker
    networks:
      - app_network
    depends_on:
      - extractor
      - mongodb

  extractor:
    build:
      context: .
      dockerfile: ./extractor/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env.docker
    networks:
      - app_network
    depends_on:
      - mongodb
    # volumes:
    #   - ./phospho-python:/phospho-python

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  ai-hub:
    build:
      context: ./ai-hub
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose AI-Hub service on port 8080
    env_file:
      - ./.env.docker
    networks:
      - app_network
    depends_on:
      - backend
      - extractor
      - mongodb
    volumes:
      # Mounting backend and phospho-python into ai-hub during runtime
      - ./backend:/backend
      - ./phospho-python:/phospho-python

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
