name: Extractor tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "extractor/**"
    branches:
      - dev

permissions:
  contents: read

jobs:
  type_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install mypy
        run: |
          pip install mypy pydantic[mypy] types-PyYAML types-cachetools types-protobuf types-pyOpenSSL types-pycurl types-requests

      - name: Get changed Python files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            extractor/**/*.py

      - name: Run mypy on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          for file in $changed_files; do
            if [[ $file == extractor/* ]]; then
              echo "Checking $file"
              mypy "$file" --ignore-missing-imports --follow-imports=silent || exit 1
            fi
          done