name: Extractor tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "extractor/**"
    branches:
      - dev

permissions:
  contents: read

jobs:
  type_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install dependencies
        run: |
          cd backend
          poetry install --with dev --no-interaction --no-root
          poetry add mypy pydantic[mypy]

      - name: Get changed Python files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            backend/**/*.py

      - name: Run mypy on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          for file in $changed_files; do
            if [[ $file == extractor/* ]]; then
              echo "Checking $file"
              mypy "$file" --ignore-missing-imports --install-types || exit 1
            fi
          done
          